<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AsutpKnowledgeBase.Core/AsutpKnowledgeBase.Core.csproj" Private="false" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.14" />
  </ItemGroup>
</Project>
