<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AsutpKnowledgeBase.Core/AsutpKnowledgeBase.Core.csproj" Private="false" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.0.2" />
    <PackageReference Include="System.IO.Packaging" Version="8.0.1" />
  </ItemGroup>
</Project>
